### ISSUE TITLE
Lack of __builtins__ And __import__ not being used

### ISSUE THREAD

**Issue by Avril112113** [EcmaXp/UMP-OC#26]
Using `import builtins` is OK over `__builtins__` but not having `__import__` being used is a problem

```python3
import builtins

def customImport(name, *args, *kwargs) :
    if name in dictOfCustomStuff:
        return dictOfCustomStuff[name]
    else:
        return __import__(name, *args, **kwargs) 

builtins.__import__ = customImport

import customThing  # not working, ImportError
customThing = __import__("customThing") # working as expected, returns customThing from dictOfCustomStuff
```
I did write that on a phone sorry :P
And if I'm wrong please enlighten me, thanks.

Besides the lack of base modules OpenPython is really good, and I am working on a OS for it, if finish it, and I did remake Open Loader for it as well :)

EDIT:
Realised the title is slightly incorrect
`__import__` does exist but does not work with the import statement `import potato`
(updated code block)

If this is just micropython then that is really sad (thought of this possibility after issue creation)

**Comment by EcmaXp** [comment]
You can't handling with __import__ hook

https://github.com/micropython/micropython/blob/440462b18ee9ee167e0bf3bf2bf18c09dc99d4a3/py/runtime.c#L1334-L1335

Because that is micropython behavior... :(

**Comment by Avril112113** [comment]
Sorry for late reply, busy with life
Thank you, i do not know how i missed that as i did a good look around and found nothing on the topic
i guess its the waiting game :/
